packages:
  - web
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@astrojs/cloudflare@14.1.7'
  - '@astrojs/compiler-binding-darwin-arm64@0.3.2'
  - '@astrojs/compiler-binding-darwin-x64@0.3.2'
  - '@astrojs/compiler-binding-linux-arm64-gnu@0.3.2'
  - '@astrojs/compiler-binding-linux-arm64-musl@0.3.2'
  - '@astrojs/compiler-binding-linux-x64-gnu@0.3.2'
  - '@astrojs/compiler-binding-linux-x64-musl@0.3.2'
  - '@astrojs/compiler-binding-wasm32-wasi@0.3.2'
  - '@astrojs/compiler-binding-win32-arm64-msvc@0.3.2'
  - '@astrojs/compiler-binding-win32-x64-msvc@0.3.2'
  - '@astrojs/compiler-binding@0.3.2'
  - '@astrojs/compiler-rs@0.3.2'
  - astro@7.1.6
